paragraph_dict = {
	"Sample" : "is this tegeleg.",
	"Education" : "Education is the basic human right. The value of education is very essential for the exercise of all other human rights. It provides freedom and empowerment to all individuals. Education is the most powerful tool by which economically and socially backward adults and children can lift themselves out of poverty line.",
	"Programming Skills" : "An example of this would be the concept of writing cascading style sheets (CSS). The concept is to write styles which apply to the top level of a site and cascade down to the lower elements in the site / page. You would then write other style rules for levels below the top level of the page and they would cascade down too. This means if there is a general style that you need to change, which is used on every page, you can change it in one place and the change will cascade to all pages that use the style and that don’t override the rule with their own rules.",
	"Ocean" : """While there is only one global ocean, the vast body of water that covers 71 percent of the Earth is geographically divided into distinct named regions. The boundaries between these regions have evolved over time for a variety of historical, cultural, geographical, and scientific reasons.\nHistorically, there are four named oceans: the Atlantic, Pacific, Indian, and Arctic. However, most countries - including the United States - now recognize the Southern (Antarctic) as the fifth ocean. The Pacific, Atlantic, and Indian are the most commonly known.""",
    "Flow State": "The quiet rhythm of the keyboard allows the mind to drift into a perfect state of flow. With each gentle keystroke, words appear smoothly across the screen like water over stone. When you stop thinking about the placement of your fingers, typing becomes as natural as breathing. Speed is not something you force; it is simply the natural result of a steady and relaxed hand.",
    "Robots" : "Robots have many uses. Factories use industrial robots to do hard work quickly and without mistakes. The military uses robots to find and get rid of bombs. If a mistake is made on a battlefield, the robot is damaged or destroyed, which is better than a person being killed. There are also domestic robots that can vacuum or cut grass.",
    "Shakespear" : "Shakespeare instructed by delighting. His plays alone (leaving mere science out of the question), contain more actual wisdom than the whole body of English learning. He is the teacher of all good-- pity, generosity, true courage, love. His bright wit is cut out “into little stars.” His solid masses of knowledge are meted out in morsels and proverbs, and thus distributed, there is scarcely a corner of the English-speaking world to-day which he does not illuminate, or a cottage which he does not enrich. His bounty is like the sea, which, though often unacknowledged, is everywhere felt. As his friend, Ben Jonson, wrote of him, “He was not of an age but for all time.” He ever kept the highroad of human life whereon all travel. He did not pick out by-paths of feeling and sentiment.",
    "The Open Road": "There is a unique kind of freedom found in a classic road trip. Driving down an open highway with the windows down, watching the landscape shift from rolling green hills to quiet desert plains, brings a deep sense of peace. It reminds us that the journey itself is often far more valuable than the final destination. Sometimes, getting lost is the best way to discover something new.",
    "Light Year" : "A light year is a distance that light travels through empty space in one year. Since the speed of light is about 300,000 km per second (about 186, 000 miles), then one light year is about 10 trillion kilometers (about 6 trillion miles). A light year is not a length of time. Light years are used in astronomy because the universe is huge.",
    "UNESCO" : """The United Nations Educational, Scientific and Cultural Organization (UNESCO) was born on 16 November 1945. UNESCO has 195 Members and 8 Associate Members and is governed by the General Conference and the Executive Board.  The Secretariat, headed by the Director-General, implements the decisions of these two bodies. The Organization has more th 50 field offices around the world and its headquarters are located in Paris.\nUNESCO’s mission is to contribute to the building of a culture of peace, the eradication of poverty, sustainable development and intercultural dialogue through education, the sciences, culture, communication and information.""",
}

def get_paragraph_topic() -> dict:
	'''To get topics name from dictionary'''
	return paragraph_dict.keys()

def get_paragraph_text(para_key) -> str:
	'''To get topic\'s text from dictionary key'''
	return paragraph_dict.get(para_key)

